#!/usr/bin/env bash
# This file is part of Cilia.
# 
# Copyright (C) 2016  Mikael Brockman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eux
shopt -s nullglob

cd "$CILIA_ROOT/projects"

while true; do
  for project in *; do
    if (
      cd "$project"
      if [ -d commits ]; then
        cd commits
        for commit in *; do
          (
            cd $commit
            if [ -d config ]; then
              if [ -d tasks ]; then
                for task in tasks/*; do
                  taskname=$(basename "$task")
                  if [ -s "$task"/request ]; then
                    request=$(cat "$task"/request)
                    "$CILIA_PATH"/do-task-request \
                      "$project" "$commit" "$taskname" "$request" \
                      &
                  fi
                done
              else
                >&2 echo "$project" "$commit" lacks tasks
              fi
            else
              >&2 echo "$project" "$commit" lacks config
            fi
          )
        done
      else
        >&2 echo "$project" lacks commits
      fi
    )
    then true
    else false
    fi
  done
  sleep 1
done