#!/usr/bin/env bash
# This file is part of Cilia.
# 
# Copyright (C) 2016  Mikael Brockman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -exu

PROJECT="$ROOT/projects/$ID"
CLONE="$PROJECT/clone"
COMMITS="$PROJECT/commits"

recent=$(
  cd "$CLONE"
  git log --pretty=format:%H "origin/$BRANCH" | head -n $DEPTH
)

for hash in $recent; do
  if [ ! -e "$PROJECT/runs/$hash/status" ] || ./needs-restart $hash; then
    exec "$@" $hash
  fi
done
