#!/usr/bin/perl -n
# This file is part of Cilia.
# 
# Copyright (C) 2016  Mikael Brockman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script is okay with input formatted like:
#
# <stdout>Hello</stdout>
# <stderr>Uh oh</stderr>
#
# It keeps those tags while escaping inside of them.

sub escape {
  my $s = shift;
  $s =~ s/&/\&amp;/g;
  $s =~ s/</\&lt;/g;
  $s =~ s/>/\&gt;/g;
  return $s;
}

if (/^<(stdout|stderr)>(.*)<\/(stdout|stderr)>$/) {
  print "<$1>", escape($2), "</$1>\n";
} else {
  print escape($_);
}
