#!/usr/bin/env bash
# This file is part of Cilia.
# 
# Copyright (C) 2016  Mikael Brockman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eux
shopt -s nullglob

project=$1
branch=$2
commit=$3

cd "$CILIA_ROOT"/projects/"$project"/commits/$commit
if [ -d work/.cilia ]; then
  ln -s "$(pwd)"/work/.cilia config
  mkdir artifacts
  mkdir -p tasks/build
  mkdir -p tasks/test
  mkdir -p tasks/up
  if [ -d config/tasks ]; then
    for task in config/tasks/*; do
      taskname=$(basename "$task")
      mkdir -p tasks/"$taskname"
    done
    if [ -s config/on-commit ]; then
      echo === $project: starting $(cat config/on-commit)
      echo start > tasks/$(cat config/on-commit)/request
    fi
  else
    >&2 echo "$project": "$commit" lacks .cilia/tasks
  fi
else
  >&2 echo "$project": lacks .cilia
fi


