#!/usr/bin/env bash
while true; do
  docker network ls -q | {
    while read x; do
      docker network inspect $x
    done
  } |
  jq -r '.[0] | select(.Name | startswith("cilia"))
              | select(.Containers | length | . == 0) | .Id' | {
    while read network; do
      if [ $network != cilia ]; do
        echo === $network: removing
        docker network rm $network
      done
    done
  }
  sleep 5
done
