#!/usr/bin/env bash
# This file is part of Cilia.
# 
# Copyright (C) 2016  Mikael Brockman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eux
shopt -s nullglob

export CILIA_DEPTH=${CILIA_DEPTH-1}

while true; do
  if [ ! -d "$CILIA_ROOT"/projects ]; then
    >&2 echo "$CILIA_ROOT"/projects: no such directory
  else
    for project in "$CILIA_ROOT"/projects/*; do
      ( ./update-project `basename "$project"` )
    done
  fi
  sleep 5
done
